// Generated by gencpp from file mytopic/topic.msg
// DO NOT EDIT!


#ifndef MYTOPIC_MESSAGE_TOPIC_H
#define MYTOPIC_MESSAGE_TOPIC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mytopic
{
template <class ContainerAllocator>
struct topic_
{
  typedef topic_<ContainerAllocator> Type;

  topic_()
    : num(0)
    , name()  {
    }
  topic_(const ContainerAllocator& _alloc)
    : num(0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _num_type;
  _num_type num;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::mytopic::topic_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mytopic::topic_<ContainerAllocator> const> ConstPtr;

}; // struct topic_

typedef ::mytopic::topic_<std::allocator<void> > topic;

typedef boost::shared_ptr< ::mytopic::topic > topicPtr;
typedef boost::shared_ptr< ::mytopic::topic const> topicConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mytopic::topic_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mytopic::topic_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mytopic::topic_<ContainerAllocator1> & lhs, const ::mytopic::topic_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mytopic::topic_<ContainerAllocator1> & lhs, const ::mytopic::topic_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mytopic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mytopic::topic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mytopic::topic_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mytopic::topic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mytopic::topic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mytopic::topic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mytopic::topic_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mytopic::topic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f785c826e41711e21d8e2636b4f53cde";
  }

  static const char* value(const ::mytopic::topic_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf785c826e41711e2ULL;
  static const uint64_t static_value2 = 0x1d8e2636b4f53cdeULL;
};

template<class ContainerAllocator>
struct DataType< ::mytopic::topic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mytopic/topic";
  }

  static const char* value(const ::mytopic::topic_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mytopic::topic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 num\n"
"string name\n"
;
  }

  static const char* value(const ::mytopic::topic_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mytopic::topic_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct topic_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mytopic::topic_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mytopic::topic_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int8_t>::stream(s, indent + "  ", v.num);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYTOPIC_MESSAGE_TOPIC_H
